iiwa:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  # Position Controllers ---------------------------------------
  joint0_position_controller:
    type: effort_controllers/JointPositionController
    joint: lbr_iiwa_joint_1
    pid: {p: 21000.0, i: 10.0, d: 0.0}
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: lbr_iiwa_joint_2
    pid: {p: 50000.0, i: 10.0, d: 0.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: lbr_iiwa_joint_3
    pid: {p: 50000.0, i: 10.0, d: 0.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: lbr_iiwa_joint_4
    pid: {p: 50000.0, i: 10.0, d: 0.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: lbr_iiwa_joint_5
    pid: {p: 50000.0, i: 10.0, d: 0.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: lbr_iiwa_joint_6
    pid: {p: 50000.0, i: 10.0, d: 0.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: lbr_iiwa_joint_7
    pid: {p: 50000.0, i: 10.0, d: 0.0}

  # Trajectory Controllers ---------------------------------------
  joint_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints: 
      - lbr_iiwa_joint_1
      - lbr_iiwa_joint_2
      - lbr_iiwa_joint_3
      - lbr_iiwa_joint_4
      - lbr_iiwa_joint_5
      - lbr_iiwa_joint_6
      - lbr_iiwa_joint_7
    gains:
      lbr_iiwa_joint_1: {p: 500,  d: 30, i: 15, i_clamp: 30} # {p: 25,  d: 5, i: 5, i_clamp: 30}
      lbr_iiwa_joint_2: {p: 200,  d: 10, i: 10, i_clamp: 30}
      lbr_iiwa_joint_3: {p: 65,  d: 10, i: 15, i_clamp: 30}
      lbr_iiwa_joint_4: {p: 31,  d: 7, i: 12, i_clamp: 30}
      lbr_iiwa_joint_5: {p: 23,  d: 3, i: 5, i_clamp: 30}
      lbr_iiwa_joint_6: {p: 13,  d: 3, i: 3, i_clamp: 30}
      lbr_iiwa_joint_7: {p: 17,  d: 2, i: 2.5, i_clamp: 10}

    constraints:
      goal_time: 0.5                   # Override default

    state_publish_rate:  25            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default
