controller_list:
  - name: /lbr_iiwa/forward_pos_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: 
      - lbr_iiwa_joint_1
      - lbr_iiwa_joint_2
      - lbr_iiwa_joint_3
      - lbr_iiwa_joint_4
      - lbr_iiwa_joint_5
      - lbr_iiwa_joint_6
      - lbr_iiwa_joint_7
      
      